### ISSUE TITLE
generatorRepository value broken for generated README.md

### ISSUE THREAD

**Issue by Req** [joonasy/rebirth#29]
1. generate typo3 project
2. open generated READM.md
3. on line 3 I see: **> Docker development environment for `.`. Generated on 21.8.2018 with [generator-rebirth v0.5.54]([object Object]).**

**Comment by joonasy** [comment]
Development environment generation has now been removed from the generator. We have now separate repositories for creating dev projects: https://github.com/joonasy/rebirth-typo3-dev https://github.com/joonasy/rebirth-wordpress-dev
