### ISSUE TITLE
Documentation update suggestions

### ISSUE THREAD

**Issue by Req** [joonasy/rebirth#30]
Considering this 

> **2.** Run the generator in your desired location, pass install directory and your project type (`typo3`, `html` or `wordpress`):
>
>    yo rebirth [my-new-project-directory] --project=typo3

If I am in directory `/projects/test/typo3generated/` and call `yo rebirth . --project=typo3` the "." is effectively used as the project name, not only the project directory. Add path and project name separately or maybe update the docs like

>**2.** Run the generator in your desired location, pass in your project name (this will also be used as the target folder for project generation) and your project type (`typo3`, `html` or `wordpress`):
>
>    yo rebirth [my-new-project] --project=typo3

**Comment by joonasy** [comment]
These texts have now been reconstructed. Currently found in Docs https://joonasy.github.io/rebirth/
