### ISSUE TITLE
Misleading info text after generation is complete

### ISSUE THREAD

**Issue by Req** [joonasy/rebirth#31]
After generating a docker project, I see `Your Docker containers are up and running.` -- that is not true, thankfully :smile: 

generator-rebirth/generators/app/index.js:619

**Comment by joonasy** [comment]
Development environment generation has now been removed from the generator. We have now separate repositories for creating projects: https://github.com/joonasy/rebirth-typo3-dev https://github.com/joonasy/rebirth-wordpress-dev
